name: Build and Deploy
on: [push]
jobs:
build-and-deploy:
	runs-on: ubuntu-latest
	steps:
	- name: Checkout ğŸ‘€
		uses: actions/checkout@v2.3.1

	- name: Setup Haxe ğŸš§
		uses: krdlab/setup-haxe@v1

	- name: Setup libs ğŸ“š
		run: |
		haxelib git zero-static https://github.com/01010111/zero-static --always --quiet
		haxelib install markdown --always --quiet

	- name: Build ğŸ”¨
		run: |
		haxe build.hxml

	- name: Push changes ğŸƒâ€â™€ï¸
		uses: ad-m/github-push-action@master
		with:
		github_token: ${{ secrets.GITHUB_TOKEN }}
		branch: ${{ github.ref }}
		force: true
	
	- name: Deploy to GitHub Pages ğŸš€
		uses: Cecilapp/GitHub-Pages-deploy@v3
		env:
		GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
		with:
		email: me@mysite.com
		build_dir: dist
		jekyll: no